version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

    volumes:
    - pgdata:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/portfolio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_CORS_ALLOWED-ORIGINS: http://localhost:5173,https://mini-portfolio-teal.vercel.app/
    depends_on:
    - db
volumes:
  pgdata: